# Centralized emoji file for Petra
# This is the ONLY place where emojis and their keywords are defined
# To add more emojis, add them to EMOJI_CATEGORIES and optionally to EMOJI_KEYWORDS

# Dictionary of emojis grouped by category (for lazy loading)
EMOJI_CATEGORIES = {
    "😊 Faces": [
        "😀", "😃", "😄", "😁", "😆", "😅", "🤣", "😂", "🙂", "🙃",
        "😉", "😊", "😇", "🥰", "😍", "🤩", "😘", "😗", "☺️", "😚",
        "😙", "🥲", "😋", "😛", "😜", "🤪", "😝", "🤑", "🤗", "🤭",
        "🤫", "🤔", "🤐", "🤨", "😐", "😑", "😶", "😏", "😒", "🙄",
        "😬", "🤥", "😌", "😔", "😪", "🤤", "😴", "😷", "🤒", "🤕",
        "🤢", "🤮", "🤧", "🥵", "🥶", "🥴", "😵", "🤯", "🤠", "🥳",
        "🥸", "😎", "🤓", "🧐", "😕", "😟", "🙁", "☹️", "😮", "😯",
        "😲", "😳", "🥺", "😦", "😧", "😨", "😰", "😥", "😢", "😭",
        "😱", "😖", "😣", "😞", "😓", "😩", "😫", "🥱", "😤", "😡",
        "😠", "🤬", "😈", "👿", "💀", "☠️", "💩", "🤡", "👹", "👺",
    ],
    "👋 Hands": [
        "👋", "🤚", "🖐️", "✋", "🖖", "👌", "🤌", "🤏", "✌️", "🤞",
        "🤟", "🤘", "🤙", "👈", "👉", "👆", "🖕", "👇", "☝️", "👍",
        "👎", "✊", "👊", "🤛", "🤜", "👏", "🙌", "👐", "🤲", "🤝",
        "🙏", "✍️", "💅", "🤳", "💪", "🦾", "🦿", "🦵", "🦶", "👂",
        "🦻", "👃", "🧠", "🫀", "🫁", "🦷", "🦴", "👀", "👁️", "👅",
        "👄", "👶", "🧒", "👦", "👧", "🧑", "👱", "👨", "🧔", "👨‍🦰",
    ],
    "❤️ Hearts": [
        "❤️", "🧡", "💛", "💚", "💙", "💜", "🖤", "🤍", "🤎", "💔",
        "❣️", "💕", "💞", "💓", "💗", "💖", "💘", "💝",
    ],
    "🍎 Food": [
        # Fruits
        "🍇", "🍈", "🍉", "🍊", "🍋", "🍌", "🍍", "🥭", "🍎", "🍏",
        "🍐", "🍑", "🍒", "🍓", "🫐", "🥝", "🍅", "🫒", "🥥", "🥑",
        # Vegetables
        "🍆", "🥔", "🥕", "🌽", "🌶️", "🫑", "🥒", "🥬", "🥦", "🧄",
        "🧅", "🥜", "🫘", "🌰",
        # Prepared food
        "🍞", "🥐", "🥖", "🫓", "🥨", "🥯", "🥞", "🧇", "🧀", "🍖",
        "🍗", "🥩", "🥓", "🍔", "🍟", "🍕", "🌭", "🥪", "🌮", "🌯",
        "🫔", "🥙", "🧆", "🥚", "🍳", "🥘", "🍲", "🫕", "🥣", "🥗",
        "🍿", "🧈", "🧂", "🥫", "🍱", "🍘", "🍙", "🍚", "🍛", "🍜",
        "🍝", "🍠", "🍢", "🍣", "🍤", "🍥", "🥮", "🍡", "🥟", "🥠",
        "🥡", "🦪", "🍦", "🍧", "🍨", "🍩", "🍪", "🎂", "🍰", "🧁",
        "🥧", "🍫", "🍬", "🍭", "🍮", "🍯",
    ],
    "🌸 Plants": [
        "💐", "🌸", "💮", "🏵️", "🌹", "🥀", "🌺", "🌻", "🌼", "🌷",
        "🌱", "🪴", "🌲", "🌳", "🌴", "🌵", "🌾", "🌿", "☘️", "🍀",
        "🍁", "🍂", "🍃", "🍄", "🌰",
    ],
    "🏠 Places": [
        "🏠", "🏡", "🏢", "🏣", "🏤", "🏥", "🏦", "🏨", "🏩", "🏪",
        "🏫", "🏬", "🏭", "🏯", "🏰", "💒", "🗼", "🗽", "⛪", "🕌",
        "🛕", "🕍", "⛩️", "🕋", "⛲", "⛺", "🌁", "🌃", "🏙️", "🌄",
        "🌅", "🌆", "🌇", "🌉", "🎠", "🎡", "🎢", "🚂", "🚃", "🚄",
    ],
    "🚗 Transport": [
        "🚗", "🚕", "🚙", "🚌", "🚎", "🏎️", "🚓", "🚑", "🚒", "🚐",
        "🛻", "🚚", "🚛", "🚜", "🏍️", "🛵", "🚲", "🛴", "🛹", "🚏",
        "🛣️", "🛤️", "⛽", "🚨", "🚥", "🚦", "🚧", "⚓", "🛟", "⛵",
        "🚤", "🛳️", "⛴️", "🛥️", "🚢", "✈️", "🛩️", "🛫", "🛬", "🪂",
        "💺", "🚁", "🚟", "🚠", "🚡", "🛰️", "🚀", "🛸",
    ],
    "💻 Objects": [
        "💻", "🖥️", "📱", "🖨️", "⌨️", "🖱️", "💾", "💿", "📀", "🎥",
        "📷", "📸", "📹", "📼", "🔍", "🔎", "🕯️", "💡", "🔦", "🏮",
        "📔", "📕", "📖", "📗", "📘", "📙", "📚", "📓", "📒", "📃",
        "📄", "📰", "🗞️", "📑", "🔖", "🏷️", "💰", "🪙", "💴", "💵",
        "💶", "💷", "💸", "💳", "🧾", "✉️", "📧", "📨", "📩", "📤",
        "📥", "📦", "📫", "📪", "📬", "📭", "📮", "🗳️", "✏️", "✒️",
        "🖋️", "🖊️", "🖌️", "🖍️", "📝", "📁", "📂", "🗂️", "📅", "📆",
        "🗒️", "🗓️", "📇", "📈", "📉", "📊", "📋", "📌", "📍", "📎",
        "🖇️", "📏", "📐", "✂️", "🗃️", "🗄️", "🗑️", "🔒", "🔓", "🔏",
        "🔐", "🔑", "🗝️", "🔨", "🪓", "⛏️", "⚒️", "🛠️", "🗡️", "⚔️",
        "🔫", "🪃", "🛡️", "🪚", "🔧", "🪛", "🔩", "⚙️", "🗜️", "⚖️",
        "🦯", "🔗", "⛓️", "🪝", "🧰", "🧲", "🪜", "⚗️", "🧪", "🧫",
        "🧬", "🔬", "🔭", "📡", "💉", "🩸", "💊", "🩹", "🩺", "🚪",
        "🛗", "🪞", "🪟", "🛏️", "🛋️", "🪑", "🚽", "🪠", "🚿", "🛁",
        "🪤", "🪒", "🧴", "🧷", "🧹", "🧺", "🧻", "🪣", "🧼", "🪥",
        "🧽", "🧯", "🛒", "🚬", "⚰️", "🪦", "⚱️", "🗿", "🪧", "🏧",
    ],
    "⭐ Symbols": [
        # Religious and zodiac symbols
        "⭐", "🌟", "✝️", "☪️", "🕉️", "☸️", "✡️", "🔯", "🕎", "☯️", "☦️", "🛐",
        "⛎", "♈", "♉", "♊", "♋", "♌", "♍", "♎", "♏", "♐",
        "♑", "♒", "♓", "🆔", "⚛️", "🉑", "☢️", "☣️", "📴", "📳",
        # Arrows and symbols
        "↩️", "↪️", "⚡", "♻️", "📛", "🔰", "🔱", "⭕", "✅", "☑️",
        "✔️", "❌", "❎", "➰", "➿", "〽️", "✳️", "❇️", "▪️", "▫️",
        "◾", "◽", "◼️", "◻️", "⬛", "⬜", "🔶", "🔷", "🔸", "🔹",
        # Additional symbols (moved from hearts)
        "💟", "☮️",
        # Extra symbols
        "💫", "💥", "💢", "💯", "🚫",
        "‼️", "⁉️", "❓", "❔", "❕", "❗", "➕", "➖", "➗", "✖️",
    ],
    "⏰ Clocks": [
        "🕛", "🕧", "🕐", "🕜", "🕑", "🕝", "🕒", "🕞", "🕓", "🕟",
        "🕔", "🕠", "🕕", "🕡", "🕖", "🕢", "🕗", "🕣", "🕘", "🕤",
        "🕙", "🕥", "🕚", "🕦", "⌛", "⏳", "⌚", "⏰", "⏱️", "⏲️",
        "🕰️",
    ],
    "🌍 Weather": [
        "🌍", "🌎", "🌏", "🌐", "🌑", "🌒", "🌓", "🌔", "🌕", "🌖",
        "🌗", "🌘", "🌙", "🌚", "🌛", "🌜", "🌝", "🌞", "⭐", "🌟",
        "🌠", "🌌", "☄️", "🔥", "💧", "🌊", "🌀", "🌈", "❄️", "⛄",
        "☃️", "💨", "💦", "☔", "☂️", "🌂", "🏖️", "🏜️", "🏝️",
        "🌡️", "⛈️", "🌩️", "🌧️", "☀️", "🌤️", "⛅", "🌥️", "☁️",
    ],
    "☕ Drinks": [
        "🍼", "🥛", "☕", "🫖", "🍵", "🍶", "🍾", "🍷", "🍸", "🍹",
        "🍺", "🍻", "🥂", "🥃", "🫗", "🥤", "🧋", "🧃", "🧉", "🧊",
    ],
    "🏀 Sports": [
        "🏀", "🏈", "⚾", "🥎", "🎾", "🏐", "🏉", "🥏", "⚽", "🎱",
        "🪀", "🏓", "🏸", "🏒", "🏑", "🥍", "🏏", "🪃", "🥅", "⛳",
        "🪁", "🏹", "🎣", "🤿", "🥊", "🥋", "🎽", "🛷", "🎿", "⛷️",
        "🏂", "🪂", "🏋️", "🤼", "🤸", "⛹️", "🤺", "🏇", "⛸️", "🏆",
        "🥇", "🥈", "🥉", "🏅", "🎖️", "🎗️", "🎫", "🎟️", "🎪",
    ],
    "🎵 Music": [
        "🎭", "🎨", "🎬", "🎤", "🎧", "🎼", "🎹", "🥁", "🪘", "🎷",
        "🎺", "🎸", "🪕", "🎻", "🎲", "🎯", "🎳", "🎮", "🕹️", "🎰",
    ],
    "🎉 Celebrations": [
        "🎀", "🎁", "🎂", "🎄", "🎆", "🎇", "🧨", "🎈", "🎉", "🎊",
        "🎋", "🎍", "🎎", "🎏", "🎐", "🎑", "🧧", "🪔", "🎃", "👻",
        "🎅", "🤶", "🧑‍🎄", "🦌", "🍀", "🎴",
    ],
    "🐶 Animals": [
        "🐶", "🐕", "🐩", "🐺", "🦊", "🦝", "🐱", "🐈", "🦁", "🐯",
        "🐅", "🐆", "🐴", "🐎", "🦄", "🦓", "🐮", "🐂", "🐃", "🐄",
        "🐷", "🐖", "🐗", "🐽", "🐏", "🐑", "🐐", "🐪", "🐫", "🦙",
        "🦒", "🐘", "🦏", "🦛", "🐭", "🐁", "🐀", "🐹", "🐰", "🐇",
        "🐿️", "🦔", "🦇", "🐻", "🐨", "🐼", "🦥", "🦦", "🦨", "🦘",
        "🦡", "🐾", "🦃", "🐔", "🐓", "🐣", "🐤", "🐥", "🐦", "🐧",
        "🕊️", "🦅", "🦆", "🦢", "🦉", "🦩", "🦚", "🦜", "🐸", "🐊",
        "🐢", "🦎", "🐍", "🐲", "🐉", "🦕", "🦖", "🐳", "🐋", "🐬",
        "🦭", "🐟", "🐠", "🐡", "🦈", "🐙", "🐚", "🐌", "🦋", "🐛",
        "🐜", "🐝", "🪲", "🐞", "🦗", "🪳", "🕷️", "🕸️", "🦂", "🦟",
        "🦀", "🦞", "🦐", "🦑",
    ],
}

# Master list of all available emojis (generated from EMOJI_CATEGORIES for compatibility)
ALL_EMOJIS = []
for category_emojis in EMOJI_CATEGORIES.values():
    ALL_EMOJIS.extend(category_emojis)

# Dictionary of emojis with search keywords
# Emojis without keywords here will still appear in the list, just won't be searchable by keyword
EMOJI_KEYWORDS = {
    # Happy faces
    "😀": ["grinning", "face", "happy", "smile"],
    "😃": ["grinning", "big eyes", "happy", "smile", "joy"],
    "😄": ["grinning", "smiling eyes", "happy", "laugh"],
    "😁": ["beaming", "grin", "happy", "smile"],
    "😆": ["laughing", "satisfied", "happy", "lol", "xd"],
    "😅": ["sweat", "grinning", "nervous", "awkward"],
    "🤣": ["rofl", "rolling", "laughing", "lol", "lmao"],
    "😂": ["joy", "tears", "laughing", "lol", "crying laughing"],
    "🙂": ["slightly smiling", "smile", "ok", "fine"],
    "🙃": ["upside down", "sarcasm", "silly", "ironic"],
    
    # Affectionate faces
    "😉": ["wink", "flirt", "playful"],
    "😊": ["blush", "smiling", "happy", "shy", "cute"],
    "😇": ["angel", "innocent", "halo", "blessed"],
    "🥰": ["love", "hearts", "adore", "affection"],
    "😍": ["heart eyes", "love", "crush", "adore"],
    "🤩": ["star struck", "excited", "amazed", "wow", "stars"],
    "😘": ["kiss", "blowing kiss", "love", "flirt"],
    "😗": ["kissing", "kiss", "smooch"],
    "☺️": ["smiling", "relaxed", "happy", "content"],
    "😚": ["kissing", "closed eyes", "kiss", "love"],
    "😙": ["kissing", "smiling eyes", "kiss"],
    "🥲": ["happy cry", "grateful", "touched", "emotional"],
    
    # Faces with tongue
    "😋": ["yummy", "delicious", "food", "tasty", "savoring"],
    "😛": ["tongue", "playful", "silly", "bleh"],
    "😜": ["wink", "tongue", "crazy", "playful", "joking"],
    "🤪": ["zany", "crazy", "wild", "goofy", "silly"],
    "😝": ["squinting", "tongue", "playful", "silly"],
    "🤑": ["money", "rich", "dollar", "greedy", "cash"],
    
    # Faces with hands
    "🤗": ["hug", "hugging", "embrace", "warm"],
    "🤭": ["giggle", "covering mouth", "oops", "shy"],
    "🤫": ["shush", "quiet", "secret", "silence"],
    "🤔": ["thinking", "hmm", "consider", "wondering"],
    
    # Neutral faces
    "🤐": ["zipper mouth", "secret", "quiet", "mute"],
    "🤨": ["raised eyebrow", "suspicious", "skeptical"],
    "😐": ["neutral", "expressionless", "meh", "blank"],
    "😑": ["expressionless", "annoyed", "unamused"],
    "😶": ["no mouth", "silent", "speechless", "mute"],
    "😏": ["smirk", "smug", "flirt", "sly"],
    "😒": ["unamused", "annoyed", "side eye", "meh"],
    "🙄": ["eye roll", "annoyed", "whatever", "bored"],
    
    # Sleeping/tired faces
    "😬": ["grimacing", "awkward", "nervous", "cringe"],
    "🤥": ["lying", "pinocchio", "lie", "liar"],
    "😌": ["relieved", "peaceful", "content", "calm"],
    "😔": ["pensive", "sad", "disappointed", "down"],
    "😪": ["sleepy", "tired", "drowsy"],
    "🤤": ["drooling", "hungry", "want", "desire"],
    "😴": ["sleeping", "zzz", "asleep", "tired"],
    
    # Sick faces
    "😷": ["mask", "sick", "medical", "covid", "flu"],
    "🤒": ["thermometer", "fever", "sick", "ill"],
    "🤕": ["bandage", "hurt", "injured", "head"],
    "🤢": ["nauseated", "sick", "gross", "disgusted"],
    "🤮": ["vomiting", "sick", "puke", "gross"],
    "🤧": ["sneezing", "sick", "cold", "tissue"],
    "🥵": ["hot", "heat", "sweating", "burning"],
    "🥶": ["cold", "freezing", "frozen", "ice"],
    "🥴": ["woozy", "drunk", "dizzy", "tipsy"],
    "😵": ["dizzy", "dead", "knocked out", "spiral"],
    "🤯": ["mind blown", "exploding", "shocked", "amazed"],
    
    # Faces with accessories
    "🤠": ["cowboy", "yeehaw", "western", "hat"],
    "🥳": ["party", "celebration", "birthday", "celebrate"],
    "🥸": ["disguised", "glasses", "mustache", "incognito"],
    "😎": ["cool", "sunglasses", "awesome", "chill"],
    "🤓": ["nerd", "geek", "glasses", "smart"],
    "🧐": ["monocle", "thinking", "inspect", "curious"],
    
    # Worried faces
    "😕": ["confused", "puzzled", "unsure"],
    "😟": ["worried", "concerned", "anxious"],
    "🙁": ["frowning", "sad", "disappointed"],
    "☹️": ["frowning", "sad", "unhappy"],
    "😮": ["surprised", "open mouth", "wow", "oh"],
    "😯": ["hushed", "surprised", "stunned"],
    "😲": ["astonished", "shocked", "wow", "surprised"],
    "😳": ["flushed", "embarrassed", "blushing", "shy"],
    "🥺": ["pleading", "puppy eyes", "please", "begging"],
    "😦": ["frowning", "open mouth", "worried"],
    "😧": ["anguished", "worried", "distressed"],
    "😨": ["fearful", "scared", "frightened", "afraid"],
    "😰": ["anxious", "sweat", "nervous", "worried"],
    "😥": ["sad", "relieved", "disappointed"],
    "😢": ["crying", "sad", "tear", "upset"],
    "😭": ["loudly crying", "sobbing", "sad", "tears"],
    "😱": ["screaming", "fear", "scared", "horror", "omg"],
    "😖": ["confounded", "frustrated", "upset"],
    "😣": ["persevering", "struggling", "frustrated"],
    "😞": ["disappointed", "sad", "dejected"],
    "😓": ["downcast", "sweat", "hard work", "tired"],
    "😩": ["weary", "tired", "frustrated", "exhausted"],
    "😫": ["tired", "exhausted", "fed up"],
    "🥱": ["yawning", "tired", "sleepy", "bored"],
    
    # Angry faces
    "😤": ["huffing", "angry", "frustrated", "triumph"],
    "😡": ["angry", "mad", "rage", "furious"],
    "😠": ["angry", "mad", "annoyed", "grumpy"],
    "🤬": ["cursing", "swearing", "angry", "mad", "symbols"],
    
    # Negative/fantasy faces
    "😈": ["devil", "evil", "smiling", "mischief", "naughty"],
    "👿": ["angry devil", "evil", "imp", "mad"],
    "💀": ["skull", "dead", "death", "skeleton"],
    "☠️": ["skull crossbones", "death", "danger", "poison"],
    "💩": ["poop", "poo", "shit", "crap"],
    "🤡": ["clown", "funny", "circus", "joker"],
    "👹": ["ogre", "monster", "japanese", "demon"],
    "👺": ["goblin", "tengu", "japanese", "mask"],
    
    # Waving hands
    "👋": ["wave", "hello", "hi", "bye", "goodbye"],
    "🤚": ["raised back", "hand", "stop"],
    "🖐️": ["hand", "fingers", "five", "high five"],
    "✋": ["raised hand", "stop", "high five"],
    "🖖": ["vulcan", "spock", "star trek", "live long"],
    
    # Hand gestures
    "👌": ["ok", "okay", "perfect", "good"],
    "🤌": ["pinched fingers", "italian", "chef kiss"],
    "🤏": ["pinching", "small", "tiny", "little"],
    "✌️": ["peace", "victory", "two", "v sign"],
    "🤞": ["crossed fingers", "luck", "hope", "wish"],
    "🤟": ["love you", "rock", "gesture", "ily"],
    "🤘": ["rock", "metal", "horns", "devil"],
    "🤙": ["call me", "shaka", "hang loose", "phone"],
    
    # Directions
    "👈": ["pointing left", "left", "direction"],
    "👉": ["pointing right", "right", "direction"],
    "👆": ["pointing up", "up", "direction"],
    "🖕": ["middle finger", "fuck", "rude", "offensive"],
    "👇": ["pointing down", "down", "direction"],
    "☝️": ["index up", "one", "point", "attention"],
    
    # Thumbs
    "👍": ["thumbs up", "like", "good", "yes", "ok", "approve"],
    "👎": ["thumbs down", "dislike", "bad", "no", "disapprove"],
    
    # Fists
    "✊": ["raised fist", "power", "solidarity", "punch"],
    "👊": ["fist bump", "punch", "bro"],
    "🤛": ["left fist", "fist bump"],
    "🤜": ["right fist", "fist bump"],
    
    # Applause and joined hands
    "👏": ["clap", "applause", "bravo", "congrats"],
    "🙌": ["raising hands", "celebration", "praise", "hooray"],
    "👐": ["open hands", "hug", "jazz hands"],
    "🤲": ["palms up", "prayer", "offering"],
    "🤝": ["handshake", "deal", "agreement", "partnership"],
    "🙏": ["pray", "please", "thank you", "hope", "namaste"],
    
    # Hands doing things
    "✍️": ["writing", "pen", "signature", "author"],
    "💅": ["nail polish", "nails", "beauty", "sassy"],
    "🤳": ["selfie", "phone", "photo", "camera"],
    
    # Body
    "💪": ["muscle", "strong", "flex", "bicep", "strength"],
    "🦾": ["mechanical arm", "robot", "prosthetic", "bionic"],
    "🦿": ["mechanical leg", "prosthetic", "bionic"],
    "🦵": ["leg", "kick", "limb"],
    "🦶": ["foot", "kick", "stomp"],
    "👂": ["ear", "listen", "hear", "hearing"],
    "🦻": ["ear aid", "hearing", "deaf"],
    "👃": ["nose", "smell", "sniff"],
    "🧠": ["brain", "smart", "think", "mind", "intelligence"],
    "🫀": ["heart organ", "anatomical", "cardio"],
    "🫁": ["lungs", "breathe", "respiratory"],
    "🦷": ["tooth", "dentist", "teeth"],
    "🦴": ["bone", "skeleton", "dog"],
    "👀": ["eyes", "look", "see", "watching", "stare"],
    "👁️": ["eye", "see", "look", "watch"],
    "👅": ["tongue", "lick", "taste"],
    "👄": ["mouth", "lips", "kiss"],
    
    # People
    "👶": ["baby", "infant", "child", "newborn"],
    "🧒": ["child", "kid", "young"],
    "👦": ["boy", "male", "child", "kid"],
    "👧": ["girl", "female", "child", "kid"],
    "🧑": ["person", "adult", "human"],
    "👱": ["blond", "blonde", "person"],
    "👨": ["man", "male", "guy", "adult"],
    "🧔": ["beard", "man", "bearded"],
    "👨‍🦰": ["man", "red hair", "ginger", "redhead"],
    
    # Hearts
    "❤️": ["red heart", "love", "like", "romance"],
    "🧡": ["orange heart", "love", "friendship"],
    "💛": ["yellow heart", "love", "friendship", "happy"],
    "💚": ["green heart", "love", "nature", "envy"],
    "💙": ["blue heart", "love", "trust", "loyalty"],
    "💜": ["purple heart", "love", "compassion"],
    "🖤": ["black heart", "love", "dark", "goth"],
    "🤍": ["white heart", "love", "pure", "clean"],
    "🤎": ["brown heart", "love", "earth"],
    "💔": ["broken heart", "heartbreak", "sad", "breakup"],
    "❣️": ["heart exclamation", "love", "emphasis"],
    "💕": ["two hearts", "love", "romance", "couple"],
    "💞": ["revolving hearts", "love", "romance"],
    "💓": ["beating heart", "love", "alive", "pulse"],
    "💗": ["growing heart", "love", "affection"],
    "💖": ["sparkling heart", "love", "excitement"],
    "💘": ["heart arrow", "cupid", "love", "romance"],
    "💝": ["heart ribbon", "gift", "love", "present"],
    "💟": ["heart decoration", "love", "ornament"],
    
    # Animals - Mammals
    "🐶": ["dog", "perro", "puppy", "pet", "cachorro"],
    "🐕": ["dog", "perro", "pet"],
    "🐩": ["poodle", "dog", "perro", "fancy"],
    "🐺": ["wolf", "lobo", "wild"],
    "🦊": ["fox", "zorro", "cute"],
    "🦝": ["raccoon", "mapache"],
    "🐱": ["cat", "gato", "kitty", "pet"],
    "🐈": ["cat", "gato", "pet"],
    "🦁": ["lion", "leon", "king", "wild"],
    "🐯": ["tiger", "tigre", "wild"],
    "🐅": ["tiger", "tigre"],
    "🐆": ["leopard", "leopardo", "jaguar"],
    "🐴": ["horse", "caballo"],
    "🐎": ["horse", "caballo", "racing"],
    "🦄": ["unicorn", "unicornio", "magic", "fantasy"],
    "🦓": ["zebra", "cebra"],
    "🐮": ["cow", "vaca", "moo"],
    "🐂": ["ox", "buey", "toro"],
    "🐃": ["water buffalo", "bufalo"],
    "🐄": ["cow", "vaca"],
    "🐷": ["pig", "cerdo", "puerco", "cochino"],
    "🐖": ["pig", "cerdo"],
    "🐗": ["boar", "jabali", "wild"],
    "🐽": ["pig nose", "cerdo", "nariz"],
    "🐏": ["ram", "carnero", "sheep"],
    "🐑": ["sheep", "oveja", "lamb"],
    "🐐": ["goat", "cabra"],
    "🐪": ["camel", "camello", "desert"],
    "🐫": ["camel", "camello", "two humps"],
    "🦙": ["llama", "alpaca"],
    "🦒": ["giraffe", "jirafa", "tall"],
    "🐘": ["elephant", "elefante", "big"],
    "🦏": ["rhino", "rinoceronte"],
    "🦛": ["hippo", "hipopotamo"],
    "🐭": ["mouse", "raton", "small"],
    "🐁": ["mouse", "raton"],
    "🐀": ["rat", "rata"],
    "🐹": ["hamster", "pet", "cute"],
    "🐰": ["rabbit", "conejo", "bunny", "easter"],
    "🐇": ["rabbit", "conejo", "bunny"],
    "🐿️": ["squirrel", "ardilla", "chipmunk"],
    "🦔": ["hedgehog", "erizo"],
    "🦇": ["bat", "murcielago", "vampire"],
    "🐻": ["bear", "oso", "teddy"],
    "🐨": ["koala", "australia", "cute"],
    "🐼": ["panda", "china", "cute", "bear"],
    "🦥": ["sloth", "perezoso", "slow"],
    "🦦": ["otter", "nutria"],
    "🦨": ["skunk", "zorrillo", "mofeta"],
    "🦘": ["kangaroo", "canguro", "australia"],
    "🦡": ["badger", "tejon"],
    "🐾": ["paw", "huella", "prints", "pet"],
    
    # Animals - Birds
    "🦃": ["turkey", "pavo", "thanksgiving"],
    "🐔": ["chicken", "pollo", "gallina", "hen"],
    "🐓": ["rooster", "gallo", "cock"],
    "🐣": ["hatching", "chick", "pollito", "baby"],
    "🐤": ["chick", "pollito", "baby"],
    "🐥": ["chick", "pollito", "front"],
    "🐦": ["bird", "pajaro", "ave"],
    "🐧": ["penguin", "pinguino", "cold"],
    "🕊️": ["dove", "paloma", "peace"],
    "🦅": ["eagle", "aguila", "freedom"],
    "🦆": ["duck", "pato"],
    "🦢": ["swan", "cisne", "elegant"],
    "🦉": ["owl", "buho", "lechuza", "wise"],
    "🦩": ["flamingo", "pink"],
    "🦚": ["peacock", "pavo real"],
    "🦜": ["parrot", "loro", "tropical"],
    
    # Animals - Reptiles and amphibians
    "🐸": ["frog", "rana", "sapo", "ribbit"],
    "🐊": ["crocodile", "cocodrilo", "alligator"],
    "🐢": ["turtle", "tortuga", "slow"],
    "🦎": ["lizard", "lagartija", "lagarto"],
    "🐍": ["snake", "serpiente", "vibora"],
    "🐲": ["dragon", "face", "chinese"],
    "🐉": ["dragon", "fantasy", "chinese"],
    "🦕": ["dinosaur", "dinosaurio", "sauropod", "brontosaurus"],
    "🦖": ["t-rex", "dinosaur", "dinosaurio", "tyrannosaurus"],
    
    # Animals - Marine
    "🐳": ["whale", "ballena", "spouting"],
    "🐋": ["whale", "ballena"],
    "🐬": ["dolphin", "delfin"],
    "🦭": ["seal", "foca"],
    "🐟": ["fish", "pez", "pescado"],
    "🐠": ["tropical fish", "pez", "nemo"],
    "🐡": ["blowfish", "pez globo"],
    "🦈": ["shark", "tiburon", "jaws"],
    "🐙": ["octopus", "pulpo"],
    "🐚": ["shell", "concha", "beach"],
    "🦀": ["crab", "cangrejo"],
    "🦞": ["lobster", "langosta"],
    "🦐": ["shrimp", "camaron", "gamba"],
    "🦑": ["squid", "calamar"],
    
    # Animals - Insects
    "🐌": ["snail", "caracol", "slow"],
    "🦋": ["butterfly", "mariposa", "pretty"],
    "🐛": ["bug", "gusano", "caterpillar", "oruga"],
    "🐜": ["ant", "hormiga"],
    "🐝": ["bee", "abeja", "honey", "miel"],
    "🪲": ["beetle", "escarabajo"],
    "🐞": ["ladybug", "mariquita", "catarina"],
    "🦗": ["cricket", "grillo"],
    "🪳": ["cockroach", "cucaracha"],
    "🕷️": ["spider", "araña"],
    "🕸️": ["spider web", "telaraña"],
    "🦂": ["scorpion", "escorpion", "alacran"],
    "🦟": ["mosquito", "zancudo"],
    
    # Plants and flowers
    "💐": ["bouquet", "flowers", "ramo", "flores"],
    "🌸": ["cherry blossom", "sakura", "flower", "pink"],
    "💮": ["white flower", "flor", "japanese"],
    "🏵️": ["rosette", "flower", "award"],
    "🌹": ["rose", "rosa", "love", "flower", "romantic"],
    "🥀": ["wilted", "flower", "dead", "sad"],
    "🌺": ["hibiscus", "flower", "tropical"],
    "🌻": ["sunflower", "girasol", "happy", "yellow"],
    "🌼": ["blossom", "flower", "daisy"],
    "🌷": ["tulip", "tulipan", "flower", "spring"],
    "🌱": ["seedling", "planta", "grow", "plant"],
    "🪴": ["potted plant", "planta", "maceta"],
    "🌲": ["evergreen", "tree", "arbol", "pine", "christmas"],
    "🌳": ["tree", "arbol", "deciduous"],
    "🌴": ["palm", "palmera", "tropical", "beach"],
    "🌵": ["cactus", "desert"],
    "🌾": ["rice", "arroz", "wheat", "grain"],
    "🌿": ["herb", "hierba", "leaf"],
    "☘️": ["shamrock", "trebol", "irish"],
    "🍀": ["four leaf clover", "trebol", "luck", "suerte"],
    "🍁": ["maple leaf", "hoja", "fall", "canada"],
    "🍂": ["fallen leaf", "hoja", "autumn", "otoño"],
    "🍃": ["leaf", "hoja", "wind", "nature"],
    "🍄": ["mushroom", "hongo", "champiñon", "seta"],
    "🌰": ["chestnut", "castaña", "nut"],
    
    # Fruits
    "🍇": ["grapes", "uvas", "wine", "fruit"],
    "🍈": ["melon", "melon", "fruit"],
    "🍉": ["watermelon", "sandia", "summer", "fruit"],
    "🍊": ["orange", "naranja", "tangerine", "mandarina", "fruit"],
    "🍋": ["lemon", "limon", "sour", "fruit"],
    "🍌": ["banana", "platano", "fruit"],
    "🍍": ["pineapple", "piña", "tropical", "fruit"],
    "🥭": ["mango", "tropical", "fruit"],
    "🍎": ["apple", "manzana", "red", "fruit"],
    "🍏": ["green apple", "manzana", "fruit"],
    "🍐": ["pear", "pera", "fruit"],
    "🍑": ["peach", "durazno", "melocoton", "fruit"],
    "🍒": ["cherries", "cerezas", "fruit"],
    "🍓": ["strawberry", "fresa", "frutilla", "fruit"],
    "🫐": ["blueberries", "arandanos", "fruit"],
    "🥝": ["kiwi", "fruit"],
    "🍅": ["tomato", "tomate", "vegetable"],
    "🫒": ["olive", "aceituna", "oliva"],
    "🥥": ["coconut", "coco", "tropical"],
    "🥑": ["avocado", "aguacate", "palta", "guacamole"],
    
    # Vegetables
    "🍆": ["eggplant", "berenjena", "vegetable"],
    "🥔": ["potato", "papa", "patata"],
    "🥕": ["carrot", "zanahoria", "vegetable"],
    "🌽": ["corn", "maiz", "elote", "choclo"],
    "🌶️": ["pepper", "chile", "hot", "spicy", "picante"],
    "🫑": ["bell pepper", "pimiento", "vegetable"],
    "🥒": ["cucumber", "pepino", "vegetable"],
    "🥬": ["leafy green", "lechuga", "vegetable"],
    "🥦": ["broccoli", "brocoli", "vegetable"],
    "🧄": ["garlic", "ajo"],
    "🧅": ["onion", "cebolla"],
    "🥜": ["peanuts", "mani", "cacahuate"],
    "🫘": ["beans", "frijoles", "porotos"],
    
    # Prepared food
    "🍞": ["bread", "pan", "food"],
    "🥐": ["croissant", "cuernito", "french", "breakfast"],
    "🥖": ["baguette", "bread", "pan", "french"],
    "🫓": ["flatbread", "pan", "pita"],
    "🥨": ["pretzel", "snack"],
    "🥯": ["bagel", "bread", "breakfast"],
    "🥞": ["pancakes", "hotcakes", "breakfast"],
    "🧇": ["waffle", "breakfast"],
    "🧀": ["cheese", "queso"],
    "🍖": ["meat", "carne", "bone"],
    "🍗": ["chicken leg", "pollo", "drumstick"],
    "🥩": ["steak", "carne", "meat", "beef"],
    "🥓": ["bacon", "tocino", "breakfast"],
    "🍔": ["hamburger", "burger", "hamburgesa", "fast food"],
    "🍟": ["fries", "papas fritas", "french fries", "fast food"],
    "🍕": ["pizza", "italian", "fast food"],
    "🌭": ["hot dog", "hotdog", "fast food"],
    "🥪": ["sandwich", "lunch"],
    "🌮": ["taco", "mexican", "mexico"],
    "🌯": ["burrito", "mexican", "wrap"],
    "🫔": ["tamale", "tamal", "mexican"],
    "🥙": ["pita", "kebab", "falafel", "gyro"],
    "🧆": ["falafel", "middle eastern"],
    "🥚": ["egg", "huevo"],
    "🍳": ["fried egg", "huevo frito", "cooking", "breakfast"],
    "🥘": ["paella", "pan", "cooking", "food"],
    "🍲": ["pot", "stew", "soup", "food"],
    "🫕": ["fondue", "cheese", "swiss"],
    "🥣": ["cereal", "bowl", "breakfast"],
    "🥗": ["salad", "ensalada", "healthy"],
    "🍿": ["popcorn", "palomitas", "movie", "cinema"],
    "🧈": ["butter", "mantequilla"],
    "🧂": ["salt", "sal"],
    "🥫": ["canned", "food", "lata"],
    "🍱": ["bento", "japanese", "lunch"],
    "🍘": ["rice cracker", "japanese"],
    "🍙": ["rice ball", "onigiri", "japanese"],
    "🍚": ["rice", "arroz", "bowl"],
    "🍛": ["curry", "rice", "indian", "japanese"],
    "🍜": ["noodles", "ramen", "fideos", "soup"],
    "🍝": ["spaghetti", "pasta", "italian"],
    "🍠": ["sweet potato", "camote", "batata"],
    "🍢": ["oden", "japanese", "skewer"],
    "🍣": ["sushi", "japanese", "fish"],
    "🍤": ["shrimp", "camaron", "tempura", "fried"],
    "🍥": ["fish cake", "narutomaki", "japanese"],
    "🥮": ["mooncake", "chinese"],
    "🍡": ["dango", "japanese", "sweet"],
    "🥟": ["dumpling", "gyoza", "asian"],
    "🥠": ["fortune cookie", "chinese"],
    "🥡": ["takeout", "chinese", "box"],
    "🦪": ["oyster", "ostra", "seafood"],
    
    # Desserts
    "🍦": ["ice cream", "helado", "soft serve"],
    "🍧": ["shaved ice", "raspado"],
    "🍨": ["ice cream", "helado", "dessert"],
    "🍩": ["donut", "dona", "doughnut", "sweet"],
    "🍪": ["cookie", "galleta", "sweet"],
    "🎂": ["birthday cake", "pastel", "cumpleaños", "celebration"],
    "🍰": ["cake", "pastel", "shortcake", "dessert"],
    "🧁": ["cupcake", "muffin", "sweet"],
    "🥧": ["pie", "pay", "tarta", "dessert"],
    "🍫": ["chocolate", "candy", "sweet"],
    "🍬": ["candy", "dulce", "sweet"],
    "🍭": ["lollipop", "paleta", "candy", "sweet"],
    "🍮": ["custard", "flan", "pudding", "dessert"],
    "🍯": ["honey", "miel", "pot"],
    
    # Drinks
    "🍼": ["baby bottle", "biberon", "milk"],
    "🥛": ["milk", "leche", "glass"],
    "☕": ["coffee", "cafe", "hot", "drink"],
    "🫖": ["teapot", "tetera", "tea"],
    "🍵": ["tea", "te", "green tea", "japanese"],
    "🍶": ["sake", "japanese", "alcohol"],
    "🍾": ["champagne", "bottle", "celebration", "party"],
    "🍷": ["wine", "vino", "red wine", "drink"],
    "🍸": ["cocktail", "martini", "drink"],
    "🍹": ["tropical drink", "cocktail", "drink"],
    "🍺": ["beer", "cerveza", "mug"],
    "🍻": ["cheers", "beer", "cerveza", "toast", "salud"],
    "🥂": ["clinking glasses", "cheers", "toast", "celebration"],
    "🥃": ["whiskey", "tumbler", "drink", "alcohol"],
    "🫗": ["pouring", "liquid", "drink"],
    "🥤": ["cup straw", "soda", "drink", "refresco"],
    "🧋": ["bubble tea", "boba", "drink"],
    "🧃": ["juice box", "jugo", "drink"],
    "🧉": ["mate", "argentina", "drink"],
    "🧊": ["ice", "hielo", "cold", "cube"],
    
    # Everyday objects
    "💻": ["laptop", "computer", "computadora", "portatil"],
    "🖥️": ["desktop", "computer", "pc", "monitor"],
    "📱": ["phone", "telefono", "celular", "mobile", "smartphone"],
    "🖨️": ["printer", "impresora"],
    "⌨️": ["keyboard", "teclado"],
    "🖱️": ["mouse", "raton", "computer"],
    "💾": ["floppy disk", "save", "guardar", "diskette"],
    "💿": ["cd", "disc", "compact"],
    "📀": ["dvd", "disc"],
    "🎥": ["movie camera", "camara", "film"],
    "📷": ["camera", "camara", "photo"],
    "📸": ["camera flash", "camara", "photo"],
    "📹": ["video camera", "camara", "record"],
    "📼": ["vhs", "videocassette", "tape"],
    "🔍": ["magnifying glass", "search", "buscar", "lupa"],
    "🔎": ["magnifying glass", "search", "buscar", "right"],
    "🕯️": ["candle", "vela", "light"],
    "💡": ["light bulb", "idea", "foco", "bombilla"],
    "🔦": ["flashlight", "linterna", "light"],
    "🏮": ["lantern", "lampara", "japanese"],
    "📔": ["notebook", "cuaderno", "decorative"],
    "📕": ["book", "libro", "red", "closed"],
    "📖": ["book", "libro", "open", "read"],
    "📗": ["book", "libro", "green"],
    "📘": ["book", "libro", "blue"],
    "📙": ["book", "libro", "orange"],
    "📚": ["books", "libros", "library", "read"],
    "📓": ["notebook", "cuaderno"],
    "📒": ["ledger", "cuaderno", "yellow"],
    "📃": ["page", "pagina", "document", "curl"],
    "📄": ["document", "documento", "page"],
    "📰": ["newspaper", "periodico", "news"],
    "🗞️": ["newspaper", "periodico", "rolled"],
    "📑": ["tabs", "bookmark", "document"],
    "🔖": ["bookmark", "marcador", "tag"],
    "🏷️": ["label", "etiqueta", "tag"],
    "💰": ["money bag", "dinero", "bolsa", "rich"],
    "🪙": ["coin", "moneda"],
    "💴": ["yen", "money", "japanese"],
    "💵": ["dollar", "dolar", "money", "cash"],
    "💶": ["euro", "money", "european"],
    "💷": ["pound", "libra", "money", "british"],
    "💸": ["money wings", "dinero", "flying", "spending"],
    "💳": ["credit card", "tarjeta", "payment", "pay"],
    "🧾": ["receipt", "recibo", "factura"],
    "✉️": ["envelope", "sobre", "mail", "letter"],
    "📧": ["email", "correo", "e-mail"],
    "📨": ["envelope", "incoming", "mail"],
    "📩": ["envelope", "arrow", "mail"],
    "📤": ["outbox", "send", "upload"],
    "📥": ["inbox", "receive", "download"],
    "📦": ["package", "paquete", "box", "delivery"],
    "📫": ["mailbox", "buzon", "mail"],
    "📪": ["mailbox", "empty", "mail"],
    "📬": ["mailbox", "mail", "letter"],
    "📭": ["mailbox", "empty", "lowered"],
    "📮": ["postbox", "mail", "red"],
    "🗳️": ["ballot box", "vote", "urna"],
    "✏️": ["pencil", "lapiz", "write"],
    "✒️": ["pen", "pluma", "ink"],
    "🖋️": ["fountain pen", "pluma", "write"],
    "🖊️": ["pen", "pluma", "ballpoint"],
    "🖌️": ["paintbrush", "pincel", "art"],
    "🖍️": ["crayon", "crayon", "color"],
    "📝": ["memo", "note", "write", "nota"],
    "📁": ["folder", "carpeta", "file"],
    "📂": ["folder", "carpeta", "open"],
    "🗂️": ["dividers", "index", "folder"],
    "📅": ["calendar", "calendario", "date"],
    "📆": ["calendar", "calendario", "tear-off"],
    "🗒️": ["notepad", "bloc", "spiral"],
    "🗓️": ["calendar", "spiral", "date"],
    "📇": ["card index", "rolodex"],
    "📈": ["chart up", "grafica", "growth", "increase"],
    "📉": ["chart down", "grafica", "decrease", "decline"],
    "📊": ["bar chart", "grafica", "stats", "graph"],
    "📋": ["clipboard", "portapapeles", "list"],
    "📌": ["pushpin", "chincheta", "pin"],
    "📍": ["pin", "location", "ubicacion", "map"],
    "📎": ["paperclip", "clip", "attach"],
    "🖇️": ["paperclips", "linked", "attach"],
    "📏": ["ruler", "regla", "measure"],
    "📐": ["triangular ruler", "escuadra", "measure"],
    "✂️": ["scissors", "tijeras", "cut"],
    "🗃️": ["card box", "file", "archive"],
    "🗄️": ["cabinet", "file", "archive"],
    "🗑️": ["trash", "basura", "delete", "bin"],
    "🔒": ["lock", "candado", "locked", "secure"],
    "🔓": ["unlock", "candado", "open"],
    "🔏": ["lock pen", "secure", "privacy"],
    "🔐": ["lock key", "secure", "password"],
    "🔑": ["key", "llave", "unlock"],
    "🗝️": ["old key", "llave", "antique"],
    "🔨": ["hammer", "martillo", "tool"],
    "🪓": ["axe", "hacha", "tool"],
    "⛏️": ["pick", "pico", "mining"],
    "⚒️": ["hammer pick", "tools"],
    "🛠️": ["tools", "herramientas", "wrench"],
    "🗡️": ["dagger", "daga", "sword", "knife"],
    "⚔️": ["swords", "crossed", "battle"],
    "🔫": ["gun", "pistol", "water gun"],
    "🪃": ["boomerang", "throw"],
    "🛡️": ["shield", "escudo", "defense"],
    "🪚": ["saw", "serrucho", "tool"],
    "🔧": ["wrench", "llave", "tool"],
    "🪛": ["screwdriver", "destornillador", "tool"],
    "🔩": ["nut bolt", "tornillo", "tool"],
    "⚙️": ["gear", "engranaje", "settings", "config"],
    "🗜️": ["clamp", "compression"],
    "⚖️": ["scale", "balanza", "balance", "justice"],
    "🦯": ["cane", "baston", "blind"],
    "🔗": ["link", "enlace", "chain"],
    "⛓️": ["chains", "cadenas"],
    "🪝": ["hook", "gancho"],
    "🧰": ["toolbox", "caja herramientas"],
    "🧲": ["magnet", "iman"],
    "🪜": ["ladder", "escalera"],
    "⚗️": ["alembic", "chemistry", "science"],
    "🧪": ["test tube", "science", "lab", "chemistry"],
    "🧫": ["petri dish", "science", "lab"],
    "🧬": ["dna", "genetics", "science"],
    "🔬": ["microscope", "microscopio", "science"],
    "🔭": ["telescope", "telescopio", "space"],
    "📡": ["satellite", "antenna", "signal"],
    "💉": ["syringe", "jeringa", "vaccine", "injection"],
    "🩸": ["blood", "sangre", "drop"],
    "💊": ["pill", "pastilla", "medicine"],
    "🩹": ["bandage", "curita", "band-aid"],
    "🩺": ["stethoscope", "doctor", "medical"],
    "🚪": ["door", "puerta", "entrance"],
    "🛗": ["elevator", "ascensor", "lift"],
    "🪞": ["mirror", "espejo"],
    "🪟": ["window", "ventana"],
    "🛏️": ["bed", "cama", "sleep"],
    "🛋️": ["couch", "sofa", "furniture"],
    "🪑": ["chair", "silla", "seat"],
    "🚽": ["toilet", "inodoro", "wc", "bathroom"],
    "🪠": ["plunger", "destapador"],
    "🚿": ["shower", "ducha", "regadera"],
    "🛁": ["bathtub", "bañera", "tina", "bath"],
    "🪤": ["mouse trap", "trampa"],
    "🪒": ["razor", "navaja", "shave"],
    "🧴": ["lotion", "locion", "bottle"],
    "🧷": ["safety pin", "imperdible", "pin"],
    "🧹": ["broom", "escoba", "clean"],
    "🧺": ["basket", "canasta", "laundry"],
    "🧻": ["toilet paper", "papel", "roll"],
    "🪣": ["bucket", "cubeta", "balde"],
    "🧼": ["soap", "jabon", "clean"],
    "🪥": ["toothbrush", "cepillo dientes"],
    "🧽": ["sponge", "esponja", "clean"],
    "🧯": ["fire extinguisher", "extintor"],
    "🛒": ["shopping cart", "carrito", "compras"],
    "🚬": ["cigarette", "cigarro", "smoking"],
    "⚰️": ["coffin", "ataud", "death"],
    "🪦": ["headstone", "tombstone", "grave"],
    "⚱️": ["urn", "urna", "funeral"],
    "🗿": ["moai", "statue", "easter island"],
    "🪧": ["placard", "sign", "letrero"],
    "🏧": ["atm", "cajero", "bank"],
    
    # Transport
    "🚗": ["car", "carro", "coche", "auto"],
    "🚕": ["taxi", "cab", "yellow"],
    "🚙": ["suv", "car", "truck"],
    "🚌": ["bus", "autobus", "camion"],
    "🚎": ["trolleybus", "bus"],
    "🏎️": ["racing car", "formula", "fast"],
    "🚓": ["police car", "policia", "cop"],
    "🚑": ["ambulance", "ambulancia", "emergency"],
    "🚒": ["fire truck", "bomberos", "fire engine"],
    "🚐": ["minibus", "van"],
    "🛻": ["pickup", "truck", "camioneta"],
    "🚚": ["truck", "camion", "delivery"],
    "🚛": ["truck", "trailer", "semi"],
    "🚜": ["tractor", "farm"],
    "🏍️": ["motorcycle", "moto", "bike"],
    "🛵": ["scooter", "moto", "vespa"],
    "🚲": ["bicycle", "bicicleta", "bike"],
    "🛴": ["scooter", "kick", "patinete"],
    "🛹": ["skateboard", "patineta", "skate"],
    "🚏": ["bus stop", "parada", "station"],
    "🛣️": ["highway", "carretera", "road"],
    "🛤️": ["railway", "train tracks", "vias"],
    "⛽": ["fuel", "gas", "gasolina", "station"],
    "🚨": ["police light", "siren", "emergency"],
    "🚥": ["traffic light", "semaforo", "horizontal"],
    "🚦": ["traffic light", "semaforo", "vertical"],
    "🚧": ["construction", "barrier", "obras"],
    "⚓": ["anchor", "ancla", "boat", "ship"],
    "🛟": ["ring buoy", "life saver", "rescue"],
    "⛵": ["sailboat", "velero", "boat"],
    "🚤": ["speedboat", "boat", "lancha"],
    "🛳️": ["cruise ship", "barco", "ship"],
    "⛴️": ["ferry", "boat", "ship"],
    "🛥️": ["motor boat", "yacht"],
    "🚢": ["ship", "barco", "boat"],
    "✈️": ["airplane", "avion", "plane", "flight"],
    "🛩️": ["small plane", "avioneta"],
    "🛫": ["departure", "takeoff", "plane"],
    "🛬": ["arrival", "landing", "plane"],
    "🪂": ["parachute", "paracaidas", "skydiving"],
    "💺": ["seat", "asiento", "airplane"],
    "🚁": ["helicopter", "helicoptero"],
    "🚟": ["suspension railway", "monorail"],
    "🚠": ["cable car", "mountain", "teleferico"],
    "🚡": ["aerial tramway", "cable car"],
    "🛰️": ["satellite", "satelite", "space"],
    "🚀": ["rocket", "cohete", "space", "launch"],
    "🛸": ["ufo", "alien", "flying saucer"],
    
    # Places and buildings
    "🏠": ["house", "casa", "home"],
    "🏡": ["house garden", "casa", "home"],
    "🏢": ["office", "oficina", "building"],
    "🏣": ["post office", "correo", "japanese"],
    "🏤": ["post office", "correo"],
    "🏥": ["hospital", "medical", "health"],
    "🏦": ["bank", "banco", "money"],
    "🏨": ["hotel", "lodging", "travel"],
    "🏩": ["love hotel", "romance"],
    "🏪": ["convenience store", "tienda", "shop"],
    "🏫": ["school", "escuela", "education"],
    "🏬": ["department store", "mall", "shopping"],
    "🏭": ["factory", "fabrica", "industrial"],
    "🏯": ["castle", "castillo", "japanese"],
    "🏰": ["castle", "castillo", "european"],
    "💒": ["wedding", "chapel", "boda", "church"],
    "🗼": ["tokyo tower", "tower", "japan"],
    "🗽": ["statue liberty", "new york", "usa"],
    "⛪": ["church", "iglesia", "religion"],
    "🕌": ["mosque", "mezquita", "islam"],
    "🛕": ["temple", "templo", "hindu"],
    "🕍": ["synagogue", "sinagoga", "jewish"],
    "⛩️": ["shinto shrine", "torii", "japanese"],
    "🕋": ["kaaba", "mecca", "islam"],
    "⛲": ["fountain", "fuente", "park"],
    "⛺": ["tent", "tienda", "camping"],
    "🌁": ["foggy", "bridge", "san francisco"],
    "🌃": ["night", "city", "stars", "noche"],
    "🏙️": ["cityscape", "ciudad", "buildings"],
    "🌄": ["sunrise", "mountain", "amanecer"],
    "🌅": ["sunrise", "beach", "amanecer"],
    "🌆": ["cityscape", "dusk", "atardecer"],
    "🌇": ["sunset", "city", "atardecer"],
    "🌉": ["bridge", "night", "puente"],
    "🎠": ["carousel", "horse", "carrusel"],
    "🎡": ["ferris wheel", "rueda", "fair"],
    "🎢": ["roller coaster", "montaña rusa", "thrill"],
    
    # Sports
    "🏀": ["basketball", "basquetbol", "ball"],
    "🏈": ["football", "american", "nfl"],
    "⚾": ["baseball", "ball", "mlb"],
    "🥎": ["softball", "ball"],
    "🎾": ["tennis", "tenis", "ball"],
    "🏐": ["volleyball", "voleibol", "ball"],
    "🏉": ["rugby", "ball"],
    "🥏": ["frisbee", "disc", "flying"],
    "⚽": ["soccer", "futbol", "football", "ball"],
    "🎱": ["pool", "billar", "8ball"],
    "🪀": ["yo-yo", "toy"],
    "🏓": ["ping pong", "table tennis"],
    "🏸": ["badminton", "racket"],
    "🏒": ["hockey", "ice", "stick"],
    "🏑": ["field hockey", "stick"],
    "🥍": ["lacrosse", "stick"],
    "🏏": ["cricket", "bat"],
    "🥅": ["goal", "net", "porteria"],
    "⛳": ["golf", "flag", "hole"],
    "🪁": ["kite", "papalote", "cometa"],
    "🏹": ["bow arrow", "archery", "arco"],
    "🎣": ["fishing", "pesca", "rod"],
    "🤿": ["diving", "buceo", "snorkel"],
    "🥊": ["boxing", "boxeo", "glove"],
    "🥋": ["martial arts", "karate", "judo"],
    "🎽": ["running shirt", "athletics"],
    "🛷": ["sled", "trineo", "snow"],
    "🎿": ["ski", "esqui", "snow", "winter"],
    "⛷️": ["skier", "skiing", "snow"],
    "🏂": ["snowboard", "snow", "winter"],
    "🏋️": ["weightlifting", "gym", "pesas"],
    "🤼": ["wrestling", "lucha"],
    "🤸": ["gymnastics", "cartwheel"],
    "⛹️": ["basketball", "bounce", "ball"],
    "🤺": ["fencing", "esgrima", "sword"],
    "🏇": ["horse racing", "jockey", "caballo"],
    "⛸️": ["ice skating", "patinaje", "winter"],
    "🏆": ["trophy", "trofeo", "winner", "champion"],
    "🥇": ["gold medal", "first", "winner", "oro"],
    "🥈": ["silver medal", "second", "plata"],
    "🥉": ["bronze medal", "third", "bronce"],
    "🏅": ["medal", "medalla", "sports"],
    "🎖️": ["military medal", "honor"],
    "🎗️": ["ribbon", "awareness", "lazo"],
    "🎫": ["ticket", "boleto", "admission"],
    "🎟️": ["admission ticket", "boleto", "entry"],
    "🎪": ["circus", "circo", "tent"],
    
    # Music and entertainment
    "🎭": ["theater", "teatro", "drama", "masks"],
    "🎨": ["art", "arte", "palette", "paint"],
    "🎬": ["clapper", "movie", "film", "cine"],
    "🎤": ["microphone", "microfono", "sing", "karaoke"],
    "🎧": ["headphones", "audifonos", "music"],
    "🎼": ["musical score", "music", "notes"],
    "🎹": ["piano", "keyboard", "music"],
    "🥁": ["drum", "tambor", "music"],
    "🪘": ["drum", "long", "percussion"],
    "🎷": ["saxophone", "saxofon", "jazz"],
    "🎺": ["trumpet", "trompeta", "music"],
    "🎸": ["guitar", "guitarra", "rock", "music"],
    "🪕": ["banjo", "music", "country"],
    "🎻": ["violin", "music", "classical"],
    "🎲": ["dice", "dado", "game", "gamble"],
    "🎯": ["dart", "target", "bullseye"],
    "🎳": ["bowling", "boliche", "pins"],
    "🎮": ["video game", "videojuego", "controller", "gaming"],
    "🕹️": ["joystick", "game", "arcade"],
    "🎰": ["slot machine", "casino", "gamble"],
    
    # Celebrations
    "🎀": ["ribbon", "lazo", "gift", "bow"],
    "🎁": ["gift", "regalo", "present", "birthday"],
    "🎄": ["christmas tree", "arbol navidad", "holiday"],
    "🎆": ["fireworks", "fuegos artificiales", "celebration"],
    "🎇": ["sparkler", "firework", "celebration"],
    "🧨": ["firecracker", "petardo", "dynamite"],
    "🎈": ["balloon", "globo", "party"],
    "🎉": ["party", "fiesta", "celebration", "confetti"],
    "🎊": ["confetti", "celebration", "party"],
    "🎋": ["tanabata", "japanese", "tree"],
    "🎍": ["pine decoration", "japanese", "new year"],
    "🎎": ["dolls", "japanese", "hinamatsuri"],
    "🎏": ["carp streamer", "japanese", "koinobori"],
    "🎐": ["wind chime", "japanese"],
    "🎑": ["moon ceremony", "japanese", "autumn"],
    "🧧": ["red envelope", "chinese", "lucky"],
    "🪔": ["diya lamp", "diwali", "indian"],
    "🎃": ["pumpkin", "calabaza", "halloween", "jack-o-lantern"],
    "👻": ["ghost", "fantasma", "halloween", "boo"],
    "🎅": ["santa", "christmas", "navidad", "claus"],
    "🤶": ["mrs claus", "christmas", "santa"],
    "🧑‍🎄": ["mx claus", "christmas", "santa"],
    "🦌": ["deer", "venado", "reindeer", "christmas"],
    "🎴": ["flower cards", "hanafuda", "japanese"],
    
    # Weather and sky
    "🌍": ["earth", "tierra", "globe", "europe", "africa"],
    "🌎": ["earth", "tierra", "globe", "americas"],
    "🌏": ["earth", "tierra", "globe", "asia"],
    "🌐": ["globe", "world", "internet", "web"],
    "🌑": ["new moon", "luna", "dark"],
    "🌒": ["waxing crescent", "luna", "moon"],
    "🌓": ["first quarter", "luna", "moon"],
    "🌔": ["waxing gibbous", "luna", "moon"],
    "🌕": ["full moon", "luna llena", "moon"],
    "🌖": ["waning gibbous", "luna", "moon"],
    "🌗": ["last quarter", "luna", "moon"],
    "🌘": ["waning crescent", "luna", "moon"],
    "🌙": ["crescent moon", "luna", "night"],
    "🌚": ["new moon face", "luna", "creepy"],
    "🌛": ["first quarter face", "luna", "moon"],
    "🌜": ["last quarter face", "luna", "moon"],
    "🌝": ["full moon face", "luna", "moon"],
    "🌞": ["sun face", "sol", "happy"],
    "⭐": ["star", "estrella", "favorite", "rating"],
    "🌟": ["glowing star", "estrella", "sparkle", "shine", "bright"],
    "🌠": ["shooting star", "estrella fugaz", "wish"],
    "🌌": ["milky way", "galaxy", "via lactea", "space"],
    "☄️": ["comet", "cometa", "space"],
    "💧": ["droplet", "gota", "water", "agua"],
    "🌊": ["wave", "ola", "ocean", "sea", "water"],
    "🌀": ["cyclone", "huracan", "spiral", "storm"],
    "❄️": ["snowflake", "nieve", "copo", "cold", "winter"],
    "⛄": ["snowman", "muñeco nieve", "winter"],
    "☃️": ["snowman", "muñeco nieve", "snow"],
    "💨": ["wind", "viento", "dash", "fast"],
    "💦": ["sweat", "water", "droplets", "splash"],
    "☔": ["umbrella", "rain", "paraguas", "lluvia"],
    "☂️": ["umbrella", "paraguas"],
    "🌂": ["closed umbrella", "paraguas"],
    "🏖️": ["beach", "playa", "umbrella", "vacation"],
    "🏜️": ["desert", "desierto", "sand"],
    "🏝️": ["island", "isla", "tropical", "palm"],
    
    # Religious symbols
    "☮️": ["peace", "peace symbol", "hippie"],
    "✝️": ["cross", "christian", "religion", "jesus"],
    "☪️": ["star crescent", "islam", "muslim", "religion"],
    "🕉️": ["om", "hindu", "buddhist", "religion"],
    "☸️": ["wheel dharma", "buddhist", "religion"],
    "✡️": ["star david", "jewish", "judaism", "religion"],
    "🔯": ["six pointed star", "jewish"],
    "🕎": ["menorah", "jewish", "hanukkah"],
    "☯️": ["yin yang", "balance", "taoism", "harmony"],
    "☦️": ["orthodox cross", "christian", "religion"],
    "🛐": ["place worship", "pray", "religion"],
    
    # Zodiac
    "⛎": ["ophiuchus", "zodiac", "astrology"],
    "♈": ["aries", "zodiac", "astrology", "ram"],
    "♉": ["taurus", "zodiac", "astrology", "bull"],
    "♊": ["gemini", "zodiac", "astrology", "twins"],
    "♋": ["cancer", "zodiac", "astrology", "crab"],
    "♌": ["leo", "zodiac", "astrology", "lion"],
    "♍": ["virgo", "zodiac", "astrology"],
    "♎": ["libra", "zodiac", "astrology", "scales"],
    "♏": ["scorpio", "zodiac", "astrology", "scorpion"],
    "♐": ["sagittarius", "zodiac", "astrology", "archer"],
    "♑": ["capricorn", "zodiac", "astrology", "goat"],
    "♒": ["aquarius", "zodiac", "astrology", "water"],
    "♓": ["pisces", "zodiac", "astrology", "fish"],
    
    # Miscellaneous symbols
    "🆔": ["id", "identity", "identification"],
    "⚛️": ["atom", "science", "physics", "nuclear"],
    "🉑": ["accept", "japanese", "ok"],
    "☢️": ["radioactive", "nuclear", "radiation", "danger"],
    "☣️": ["biohazard", "danger", "toxic", "biological"],
    "📴": ["mobile off", "phone off", "silent"],
    "📳": ["vibration", "phone", "mobile"],
    
    # Clocks
    "🕛": ["twelve oclock", "clock", "time", "12"],
    "🕧": ["twelve thirty", "clock", "time", "12:30"],
    "🕐": ["one oclock", "clock", "time", "1"],
    "🕜": ["one thirty", "clock", "time", "1:30"],
    "🕑": ["two oclock", "clock", "time", "2"],
    "🕝": ["two thirty", "clock", "time", "2:30"],
    "🕒": ["three oclock", "clock", "time", "3"],
    "🕞": ["three thirty", "clock", "time", "3:30"],
    "🕓": ["four oclock", "clock", "time", "4"],
    "🕟": ["four thirty", "clock", "time", "4:30"],
    "🕔": ["five oclock", "clock", "time", "5"],
    "🕠": ["five thirty", "clock", "time", "5:30"],
    "🕕": ["six oclock", "clock", "time", "6"],
    "🕡": ["six thirty", "clock", "time", "6:30"],
    "🕖": ["seven oclock", "clock", "time", "7"],
    "🕢": ["seven thirty", "clock", "time", "7:30"],
    "🕗": ["eight oclock", "clock", "time", "8"],
    "🕣": ["eight thirty", "clock", "time", "8:30"],
    "🕘": ["nine oclock", "clock", "time", "9"],
    "🕤": ["nine thirty", "clock", "time", "9:30"],
    "🕙": ["ten oclock", "clock", "time", "10"],
    "🕥": ["ten thirty", "clock", "time", "10:30"],
    "🕚": ["eleven oclock", "clock", "time", "11"],
    "🕦": ["eleven thirty", "clock", "time", "11:30"],
    "⌛": ["hourglass", "time", "waiting", "sand"],
    "⏳": ["hourglass flowing", "time", "waiting", "sand"],
    "⌚": ["watch", "time", "wristwatch"],
    "⏰": ["alarm clock", "time", "wake up", "morning"],
    "⏱️": ["stopwatch", "time", "timer", "sports"],
    "⏲️": ["timer clock", "time", "countdown", "cooking"],
    "🕰️": ["mantelpiece clock", "time", "antique"],
    
    # Weather
    "🌡️": ["thermometer", "temperature", "weather", "fever"],
    "⛈️": ["thunderstorm", "rain", "weather", "lightning"],
    "🌩️": ["lightning", "thunder", "storm", "weather"],
    "🌧️": ["rain", "rainy", "weather", "cloud"],
    "☀️": ["sun", "sunny", "weather", "bright", "hot"],
    "🌤️": ["sun clouds", "partly cloudy", "weather"],
    "⛅": ["sun cloud", "partly cloudy", "weather"],
    "🌥️": ["sun behind cloud", "cloudy", "weather"],
    "☁️": ["cloud", "cloudy", "weather", "overcast"],
    
    # Arrows and symbols
    "↩️": ["back arrow", "return", "undo"],
    "↪️": ["forward arrow", "redo", "next"],
    "⚡": ["lightning", "bolt", "electricity", "power", "fast", "zap"],
    "♻️": ["recycle", "environment", "green", "eco"],
    "📛": ["name badge", "id", "tag"],
    "🔰": ["beginner", "japanese", "new", "starter"],
    "🔱": ["trident", "poseidon", "neptune", "emblem"],
    "⭕": ["circle", "red circle", "hollow"],
    "✅": ["check", "done", "complete", "yes", "correct"],
    "☑️": ["check box", "done", "complete", "yes"],
    "✔️": ["check mark", "done", "correct", "yes"],
    "❌": ["cross", "no", "wrong", "error", "delete", "x"],
    "❎": ["cross mark", "no", "wrong", "error"],
    "➰": ["curly loop", "loop"],
    "➿": ["double curly loop", "loop"],
    "〽️": ["part alternation", "japanese"],
    "✳️": ["eight spoked asterisk", "star"],
    "❇️": ["sparkle", "star", "shine"],
    "▪️": ["black square", "small", "dot"],
    "▫️": ["white square", "small", "dot"],
    "◾": ["black medium square"],
    "◽": ["white medium square"],
    "◼️": ["black square", "medium"],
    "◻️": ["white square", "medium"],
    "⬛": ["black large square", "dark"],
    "⬜": ["white large square", "light"],
    "🔶": ["orange diamond", "large"],
    "🔷": ["blue diamond", "large"],
    "🔸": ["orange diamond", "small"],
    "🔹": ["blue diamond", "small"],
    # Transport emojis (missing)
    "🚂": ["locomotive", "train", "steam", "locomotora", "tren", "vapor"],
    "🚃": ["railway car", "train", "wagon", "vagon", "tren"],
    "🚄": ["high speed train", "bullet train", "tren alta velocidad", "shinkansen"],
    # Weather emojis (missing)
    "🔥": ["fire", "flame", "hot", "fuego", "llama", "caliente", "lit"],
    "🌈": ["rainbow", "arcoiris", "arco iris", "colors", "colores"],
    # Symbol emojis (missing)
    "💫": ["dizzy", "star", "estrella", "mareado", "sparkle"],
    "💥": ["collision", "boom", "explosion", "bang", "colision", "choque"],
    "💢": ["anger", "angry", "enojo", "enfado", "ira"],
    "💯": ["hundred", "perfect", "score", "cien", "perfecto", "100"],
    "🚫": ["prohibited", "forbidden", "no", "prohibido", "ban"],
    "‼️": ["exclamation", "double", "warning", "exclamacion", "doble", "alerta"],
    "⁉️": ["exclamation question", "interrobang", "surprise", "sorpresa"],
    "❓": ["question", "pregunta", "what", "que"],
    "❔": ["question", "white", "pregunta", "blanco"],
    "❕": ["exclamation", "white", "exclamacion", "blanco"],
    "❗": ["exclamation", "warning", "exclamacion", "alerta", "atencion"],
    "➕": ["plus", "add", "mas", "suma", "agregar"],
    "➖": ["minus", "subtract", "menos", "resta"],
    "➗": ["divide", "division", "dividir"],
    "✖️": ["multiply", "times", "x", "multiplicar", "por"],
}

def search_emojis(query, emoji_list):
    """
    Search for emojis matching the query.
    Return a list of matching emojis.
    """
    if not query:
        return emoji_list
    
    query = query.lower().strip()
    results = []
    
    for emoji in emoji_list:
        # Search in keywords
        keywords = EMOJI_KEYWORDS.get(emoji, [])
        if any(query in keyword.lower() for keyword in keywords):
            results.append(emoji)
    
    return results
